fikrin/Fikrin/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('write/', include('posting.urls')),

    



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

fikrin/authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('profile/', views.profile, name='profile'),
    path('password-change/', views.change_password, name='change_password'),
    path('creater_details/<str:username>/', views.creater_details, name='creater_details'),
    path('about/',views.aboutme, name='aboutme')
]

fikrin/posting/urls.py
from django.urls import path
from . import views


app_name = 'posting'

urlpatterns = [
    path('add-quote/', views.add_quote, name='add_quote'),
    path('edit_post/<int:post_id>/', views.edit_post_view, name='edit_post'),
    path('delete_post/', views.delete_post_view, name='delete_post'),
    path('like_post/<int:post_id>/', views.like_post, name='like_post'),
    path('unlike_post/<int:post_id>/', views.unlike_post, name='unlike_post'),
    path('comment_view/<int:item_id>/', views.comment_view, name='comment_view'),
    path('delete_comment/', views.delete_comment, name='delete_comment'),
    path('replay_view/<int:item_id>/<int:parent_comment_id>/', views.replay_view, name='replay_view'),

]

fikrin/templates/aboutme.html
{% extends 'base.html' %}

{% load static %}

{% block 'title' %}about us{% endblock 'title' %}

{% block 'content' %}

<style>
.container{
    font-family: Arial, sans-serif;
    line-height: 1.6;
    background-color: #f0f0f0;
    margin: 0;
    padding: 0;
}
header {
    background-color: #000157;
    color: #fff;
    text-align: center;
    padding: 20px;
}

.container {
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
}

h1 {
    color: #d5e0eb;
}

p {
    margin-bottom: 20px;
}

.social-links {
    display: flex;
    justify-content: center;
    margin-top: 30px;
}

.social-links a {
    display: inline-block;
    margin: 10px;
    height: 40px;
    color: #000157;
    border-radius: 50%;
    text-align: center;
    line-height: 40px;
    font-size: 20px;
    text-decoration: none;
}

/* .social-links a:hover {
    background-color: #000157;
} */
</style>

<header>
    <h1>About Us</h1>
    <a href="{% url 'authentication:home' %}"> 
        <i class="bi bi-house position-absolute text-light" style="top: 5px; left: 15px; font-size: small;"></i></a>
</header>

<div class="container pt-5">
        

🌟 Welcome to Fikrin, an innovative social platform that promises to redefine your reading experience and ignite your
 passion for literature. 📚✨<br><br>

📖 <b>Explore Limitless Possibilities</b><br>
At Fikrin, we invite you to dive into a vast database of books, annotations, quotes, and reviews, all waiting to be explored.
 Uncover hidden literary gems, embark on thrilling adventures, and unravel profound narratives from a plethora of genres. <br><br>

🖊️ <b>Express and Share</b><br>
Our unique platform isn't just about reading; it's about embracing your inner writer. Sign up to unleash your creativity
 and contribute your thoughts, ideas, and interpretations to our ever-growing database. Share your personal annotations,
  craft insightful reviews, and even pen down your favorite quotes to inspire fellow readers. <br><br>

🔍 <b>Discover Beloved Investigators</b><br>
Ever wondered about the fictional private investigators that capture the imaginations of both writers and readers alike?
 Fikrin offers you the chance to uncover these enigmatic characters, delving into the minds of creators and appreciators
  as you unravel their mysteries and adventures. <br><br>

🤝 <b>Community and Connection</b><br>
Fikrin isn't just a website; it's a community of like-minded individuals who are passionate about the magic of words.
 Connect with fellow book enthusiasts, exchange ideas, and engage in meaningful
  discussions that enrich your literary journey. <br><br>

🌐 <b>Seamless Experience</b><br>
Our user-friendly interface ensures that navigating Fikrin is a breeze. Whether you're seeking new books to devour,
 sharing your insights, or engaging in captivating conversations, our platform's intuitive design ensures a seamless
  experience every step of the way. <br><br>

🌈 <b>Your Gateway to Imagination</b><br>
Fikrin isn't just an Indian social website; it's a portal to a world of imagination, knowledge, and connection.
 It's where literature comes alive, and where your love for books finds a home. <br><br>

Join us on this extraordinary journey as we celebrate the power of words, foster creativity,
 and build a vibrant community of readers and writers. 
 Experience Fikrin today and let your literary adventure begin! 📚🌍✍️
        
<div class="social-links">
    <a href="https://www.instagram.com/fikrin.__/" class="text-decoration-none pt-0">Follow us</a>
    <a href="https://www.instagram.com/fikrin.__/" target="_blank" title="Instagram" class="pt-0"><i class="fab fa-instagram"></i></a>
</div>

</div>


{% endblock 'content' %}

fikrin/templates/cmd_box.html
{% extends 'base.html' %}

{% load static %}
{% block 'title' %}comments{% endblock 'title' %}
{% block 'content' %}

<style>
/* Beautiful Comment Box Styles */

.comment-box {
  margin-top: 0;
  padding-top: 0;
  max-width: 600px;
  background-color: #f9f9f9;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  border-radius: 10px;
  padding-left: 20px;
  padding-right: 20px;
  padding-bottom: 20px;
  font-family: Arial, sans-serif;
}

.comment-box .main-header {
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid #ccc;
  padding-bottom: 10px;
  margin-bottom: 10px;
  position: sticky;
  top: 0;
  background-color: #f9f9f9;
  z-index: 1;
}

.comment-box .header {
    padding-top: 20px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-bottom: 1px solid #ccc;
    padding-bottom: 10px;
    margin-bottom: 10px;
    background-color: #f9f9f9;
    z-index: 1;
}

.comment-box .header h6 {
  font-size: 15px;
  color: #333;
}

.comment-box .header a {
  color: #888;
  text-decoration: none;
}

.comment-box .header a:hover {
  color: #555;
}

.comment-box .comment-content {
  margin-bottom: 20px;
}

.comment-box .comment-content p {
  color: #333;
  line-height: 1.6;
}

.comment-box .comment-content .comment-info {
  color: #888;
  font-size: 14px;
}

.comment-box .comment-content .comment-info i {
  margin-right: 5px;
}

.comment-box .comment-form {
  display: flex;
  align-items: center;
  margin-bottom: 20px;
}

.comment-box .comment-form textarea {
    flex: 1;
    resize: none;
    border: 1px solid #ccc;
    border-radius: 20px;
    padding-top: 5px;
    font-size: 14px;
    padding-left: 15px;
    height: 38px;
}

.comment-box .comment-form button {
    margin-left: 10px;
    background-color: #fff;
    color: #1b0dbe;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    font-size: 23px;
}

.comment-box .comment {
  border-bottom: 1px solid #ccc;
  margin-bottom: 15px;
  padding-bottom: 15px;
}

.comment-box .comment:last-child {
  border-bottom: none;
  margin-bottom: 0;
  padding-bottom: 0;
}

.comment-box .comment .comment-info {
  color: #888;
  font-size: 14px;
}

.comment-box .comment .comment-info i {
  margin-right: 5px;
}

.comment-box .comment .comment-content {
  margin-top: 10px;
}

.comment-box .comment .comment-content p {
  color: #333;
  line-height: 1.6;
}

.comment-box .comment .delete-comment-button {
  color: #888;
  font-size: 15px;
  border: none;
  background: none;
  margin-left: 10px;
  cursor: pointer;
}

.comment-box .comment .delete-comment-button:hover {
  color: red;
}
</style>

<div class="container p-0">
  <div class="comment-box">
    <div class="main-header">
        <div class="header">
            <h6 class="text-center">Comments</h6>
            <a href="{% url 'authentication:home' %}" id="close-noti-button">
                <i class="bi bi-x-circle-fill"></i>
            </a>
        </div>

        <div class="content_text">
          <p style="white-space: pre-wrap;">{{ item.content_text }}</p>
        </div>

        <form class="comment-form" method="post" action="{% url 'posting:comment_view' post.id %}">
            {% csrf_token %}
            <textarea name="comment_text" placeholder="Write a comment..." required minlength="1"></textarea>
            <button type="submit"><i class="bi bi-check2"></i></button>
        </form>
    </div>

    <div class="comments-section">
      {% for cmt in comments %}
      <div class="comment">
        <div class="comment-info">
          <img src="{% static 'img/profile.jpg' %}" class="rounded-circle border border-dark me-2" width="35" height="35" alt="Profile Image">
          {{ cmt.commenter }}
          {% if request.user.is_authenticated and request.user.id == cmt.commenter.id %}
            <button class="delete-comment-button" onclick="confirmDelete('{{ cmt.id }}')" style="position: absolute; right: 25px;">
              <i class="bi bi-trash"></i>
            </button>
          {% endif %}
        </div>

        <div class="comment-content">
          <p>{{ cmt.comment_content }}</p>
          <small class="ms-0 text-muted">{{ cmt.comment_time|timesince }} ago</small>
          <small style="position: absolute; right: 25px;">
            <a href="{% url 'posting:replay_view' post.id cmt.id %}" class="text-decoration-none">
                {{ cmt.replies.count }} {{ cmt.replies.count|pluralize:"Reply,Replies" }}
            </a>
        </small>
        </div>

      </div>
      {% endfor %}
    </div>

  </div>
</div>

<script>
function confirmDelete(postId) {
  if (confirm("Do you want to delete this?")) {
    // Redirect to the delete post URL
    window.location.href = "{% url 'posting:delete_comment' %}?post_id=" + postId;
  }
}
</script>

{% endblock 'content' %}

fikrin/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block 'title' %}Fikrin{% endblock 'title' %}

{% block 'content' %}

<section>

  {% include 'header.html' %}
  {% include 'sidebar.html' %}

<!-- Add the following CSS style to style the copy message -->
<style>
  #copyMessage {
      display: none;
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      padding: 10px 20px;
      background-color: #ffffff;
      border: 1px solid #dddddd;
      border-radius: 5px;
      box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
      font-weight: bold;
      font-size: 13px;
      color: #150046;
      z-index: 9999;
  }

    /* Style for the pen and trash icons */
    .icon-container {
        background-color: #f8f9fa;
        border-radius: 50%;
    }

    .icon-container i {
        font-size: 18px;
        color: #6c757d;
        cursor: pointer;
        transition: color 0.2s;
    }

    .icon-container i:hover {
        color: #030b7a;
    }


</style> 


  <div class="container">
    <div class="row pb-3">
      {% for item in posts %}
      <div class="col-sm-6 mt-3 mb-sm-0">
        <div class="card shadow-lg p-1 bg-body rounded">
          <div class="card-body">
            <div class="card-title">
              {% if request.user.is_authenticated and request.user.username == item.creater %}
              <div class="icon-container position-absolute" style="right: 25px; bottom: 65px;">
                <i class="bi bi-pen" data-bs-toggle="modal" data-bs-target="#edit_quotes{{ item.id }}" data-bs-placement="right"></i>
                <i class="bi bi-trash3 ms-4" onclick="confirmDelete('{{ item.id }}')"></i></div>
                {% endif %}
                <script>
                  function confirmDelete(postId) {
                      if (confirm("Do you want to delete this post?")) {
                          // Redirect to the delete post URL
                          window.location.href = "{% url 'posting:delete_post' %}?post_id=" + postId;
                      }
                  }
              </script>

              {% if item.profile_pic %} 
              <a href="{% if user.is_authenticated %}{% url 'authentication:creater_details' item.creater %}{% endif %}" style="text-decoration:none;">
                <img src="{{ item.profile_pic.url }}" alt="Profile Picture" class="rounded-5 me-4" width="45" height="45">
            </a>
            
              {% else %}
              
              <a href="{% if user.is_authenticated %}{% url 'authentication:creater_details' item.creater %}{% endif %}" style="text-decoration:none;">
              <img src="{% static 'img/profile.jpg' %}" alt="Default Profile Picture" class="rounded-5 me-4" width="45" height="45">
            </a>
              {% endif %}

              <a href="{% if user.is_authenticated %}{% url 'authentication:creater_details' item.creater %}{% endif %}" class="fw-bold text-dark" style="text-decoration: none;">{{item.creater}}</a>
            </div>
            <div class="card-text mt-4" {% if user.is_authenticated %} ondblclick="copyContent('{{ item.content_text|escapejs }}');" {% endif %}>

            <style>
              .content {
                overflow: hidden;
                max-height: 195px; /* Adjust this value as needed */
              }
            </style>
            <div class="content">
              <p style="white-space: pre-wrap;">{{ item.content_text }}</p>
            </div>
            <button class="btn btn-sm btn-link text-decoration-none" onclick="toggleContent(this)"
            style="padding:0;">Read More</button>


          </div>
          <!-- Add the copy message element -->
          <div id="copyMessage">Content copied!</div>

            <p class="card-text mt-2"><small class="text-body-secondary fw-lighter">
              Last updated {{ item.date_created|timesince }} ago
            </small></p>
            <div>
              <div class="row">
              <div class="col">
                {% if item.likers.count > 0 %}
                <small class="fst-italic">{{item.likers.count}} {{ item.likers.count|pluralize:"like,likes" }}</small>
                {% endif %}
                {% if item.comments.count > 0 %}
                <small class="ms-2 fst-italic">{{item.comments.count}} {{ item.comments.count|pluralize:"comment,comments" }}</small>
                {% endif %}
              </div>
            </div>
            </div>
          </div>
          <div class="card-footer text-body-secondary align-items-center">
            <div class="row align-items-center mt-1">
              <div class="col text-center">
                    <div>
                        {% if user in item.likers.all %}
                        {% if user.is_authenticated %}
                          <a href="{% url 'posting:unlike_post' item.id %}" class="cancel text-danger text-decoration-none text-end" onclick="toggleLike({{ forloop.counter0 }}, {{ item.id }})">{% endif %}
                            <i class="bi bi-heart-fill text-danger"></i>
                            <small class="text-danger"><b>Liked</b></small>
                          </a>
                        {% else %} {% if user.is_authenticated %}
                          <a href="{% url 'posting:like_post' item.id %}" class="like text-danger text-decoration-none text-end" onclick="toggleLike({{ forloop.counter0 }}, {{ item.id }})"> {% endif %}
                            <i class="bi bi-heart text-danger"></i>
                            <small class="text-danger"><b>Like</b></small>
                          </a> 
                        {% endif %}
                      </div>
              </div>
              
              <div class="col text-center">
                <!-- <a href="{% url 'posting:comment_view' item.id %}" class="text-primary text-decoration-none">Comments</a> -->
            </div>      
              <div class="col text-start  text-dark">
                <!-- <i class="bi bi-share-fill me-2"></i> -->
                <!-- <a class="text-dark" href="#" style="text-decoration:none; color:gray;"><small>Share</small></a> -->
                {% if user.is_authenticated %}
                <small><a href="{% url 'posting:comment_view' item.id %}" class="text-decoration-none" style="color: #000157;"><b>Comments</b></a></small>
                {% else %}
                <small><a class="text-decoration-none" style="color: #000157;"><b>Comments</b></a></small>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>

              <!-- Modal for Editing Post Content -->
              <div class="modal fade" id="edit_quotes{{ item.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Edit your quote</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form method="post" action="{% url 'posting:edit_post' item.id %}">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <textarea class="form-control" name="edit_text" required minlength="50" style="height: 120px;">{{ item.content_text }}</textarea>
                                  </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal for Editing Post Content End -->

      {% endfor %}

    </div>
    </div>
  </div>

</section>

 <!-- quotes popup -->


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Write a qoute</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="post" action="{% url 'posting:add_quote' %}">
          {% csrf_token %}
          <div class="mb-3">
            <textarea class="form-control" name="content-text" required minlength="50" style="height: 120px;"></textarea>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Save</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </form>
      </div>
      
      </div>
  </div>
</div>

 <!-- quotes popup end-->


<!-- quote icone start -->

<div class="quotes-icon" style="position:fixed; right: 1%; bottom: 1%;" >
  <a href="#" class="btn btn-link" title="Quotes" {% if user.is_authenticated %} data-bs-toggle="modal" {% endif %}
   data-bs-target="#exampleModal" data-bs-placement="right">
  <img src="{% static 'img/write.png' %}" alt="">
  </a>
</div> 


<!-- like action js start -->
<script>
// Initialize an array to store the like states for each card
let isLikedArray = new Array({{ posts|length }}).fill(false);

function toggleLike(cardIndex) {
  const likeButton = document.querySelectorAll('.like')[cardIndex];
  const cancelButton = document.querySelectorAll('.cancel')[cardIndex];

  if (isLikedArray[cardIndex]) {
    isLikedArray[cardIndex] = false;
    likeButton.style.display = 'inline-block';
    cancelButton.style.display = 'none';
    // Add code here to handle the cancellation of the like for the specific card (e.g., make an API call).
  } else {
    isLikedArray[cardIndex] = true;
    likeButton.style.display = 'none';
    cancelButton.style.display = 'inline-block';
    // Add code here to handle the liking action for the specific card (e.g., make an API call).
  }
}

</script>
<!-- like action js end -->


<!-- copy content_text -->
<script>
function copyContent(text) {
    const textArea = document.createElement("textarea");
    textArea.value = text;
    document.body.appendChild(textArea);
    textArea.select();
    document.execCommand("copy");
    document.body.removeChild(textArea);
    showCopyMessage();
}

function showCopyMessage() {
    const copyMessage = document.getElementById("copyMessage");
    copyMessage.style.display = "block";
    setTimeout(function () {
        copyMessage.style.display = "none";
    }, 2000);
}

</script>
<!-- copy content_text end -->


<!-- read more script -->
<script>
  function toggleContent(button) {
    var content = button.previousElementSibling;

    if (content.style.overflow === "hidden") {
      content.style.overflow = "visible";
      content.style.maxHeight = "none";
      button.innerText = "Read Less";
    } else {
      content.style.overflow = "hidden";
      content.style.maxHeight = "195px"; // Adjust this value to match initial height
      button.innerText = "Read More";
    }
  }

  document.addEventListener("DOMContentLoaded", function() {
    var contentDivs = document.querySelectorAll(".content");
    
    contentDivs.forEach(function(contentDiv) {
      var words = contentDiv.textContent.trim().split(/\s+/).length;
      var button = contentDiv.nextElementSibling;
      
      if (words <= 50) {
        button.style.display = "none";
      }
    });
  });
</script>

<!-- pwa script -->

<script>
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/static/sw.js')
    .then(registration => {
      console.log('Service Worker registered with scope:', registration.scope);
    })
    .catch(error => {
      console.error('Service Worker registration failed:', error);
    });
  }
</script>

<script>
  window.addEventListener('beforeinstallprompt', event => {
    event.preventDefault();
    const installButton = document.getElementById('install-button');
    installButton.style.display = 'block';
    installButton.addEventListener('click', () => {
      event.prompt();
    });
  });
</script>

{% endblock 'content' %}

fikrin/templates/replies.html
{% extends 'base.html' %}

{% load static %}

{% block 'content' %}

<style>
    /* Beautiful Comment Box Styles */
    
    .comment-box {
      margin-top: 0;
      padding-top: 0;
      max-width: 600px;
      background-color: #f9f9f9;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      border-radius: 10px;
      padding-left: 20px;
      padding-right: 20px;
      padding-bottom: 20px;
      font-family: Arial, sans-serif;
    }
    
    .comment-box .main-header {
      justify-content: space-between;
      align-items: center;
      border-bottom: 1px solid #ccc;
      padding-bottom: 10px;
      margin-bottom: 10px;
      position: sticky;
      top: 0;
      background-color: #f9f9f9;
      z-index: 1;
    }
    
    .comment-box .header {
        padding-top: 20px;
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-bottom: 1px solid #ccc;
        padding-bottom: 10px;
        margin-bottom: 10px;
        background-color: #f9f9f9;
        z-index: 1;
    }
    
    .comment-box .header h6 {
      font-size: 15px;
      color: #333;
    }
    
    .comment-box .header a {
      color: #888;
      text-decoration: none;
    }
    
    .comment-box .header a:hover {
      color: #555;
    }
    
    .comment-box .comment-content {
      margin-bottom: 20px;
    }
    
    .comment-box .comment-content p {
      color: #333;
      line-height: 1.6;
    }
    
    .comment-box .comment-content .comment-info {
      color: #888;
      font-size: 14px;
    }
    
    .comment-box .comment-content .comment-info i {
      margin-right: 5px;
    }
    
    .comment-box .comment-form {
      display: flex;
      align-items: center;
      margin-bottom: 20px;
    }
    
    .comment-box .comment-form textarea {
        flex: 1;
        resize: none;
        border: 1px solid #ccc;
        border-radius: 20px;
        padding-top: 5px;
        font-size: 14px;
        padding-left: 15px;
        height: 38px;
    }
    
    .comment-box .comment-form button {
        margin-left: 10px;
        background-color: #fff;
        color: #1b0dbe;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 23px;
    }
    
    .comment-box .comment {
      border-bottom: 1px solid #ccc;
      margin-bottom: 15px;
      padding-bottom: 15px;
    }
    
    .comment-box .comment:last-child {
      border-bottom: none;
      margin-bottom: 0;
      padding-bottom: 0;
    }
    
    .comment-box .comment .comment-info {
      color: #888;
      font-size: 14px;
    }
    
    .comment-box .comment .comment-info i {
      margin-right: 5px;
    }
    
    .comment-box .comment .comment-content {
      margin-top: 10px;
    }
    
    .comment-box .comment .comment-content p {
      color: #333;
      line-height: 1.6;
    }
    
    .comment-box .comment .delete-comment-button {
      color: #888;
      font-size: 15px;
      border: none;
      background: none;
      margin-left: 10px;
      cursor: pointer;
    }
    
    .comment-box .comment .delete-comment-button:hover {
      color: red;
    }
    </style>


<div class="container p-0">
    <div class="comment-box">
        <!-- Header for reply view -->
        <div class="main-header">
            <div class="header">
                <h6 class="text-center">Replies to {{ parent_comment.commenter }}</h6>
                <a href="{% url 'authentication:home' %}" id="close-noti-button">
                    <i class="bi bi-x-circle-fill"></i>
                </a>
            </div>
            <div class="comment-content">
                <p>{{ parent_comment.comment_content }}</p>
            </div>
                    
            <form class="comment-form" method="post" action="{% url 'posting:replay_view' post.id parent_comment.id %}">
                {% csrf_token %}
                <input type="hidden" name="parent_comment_id" value="{{ parent_comment.id }}">
                <textarea name="comment_text" placeholder="Write a reply..." required minlength="1"></textarea>
                <button type="submit"><i class="bi bi-check2"></i></button>
            </form>
        
        </div>
        <!-- End of Header -->

        <div class="comments-section">
            {% for reply in comments %}
            <div class="comment">
                <div class="comment-info">
                    <img src="{% static 'img/profile.jpg' %}" class="rounded-circle border border-dark me-2" width="35" height="35" alt="Profile Image">
                    {{ reply.commenter }}
                    {% if request.user.is_authenticated and request.user.id == reply.commenter.id %}
                    <button class="delete-comment-button" onclick="confirmDelete('{{ reply.id }}')" style="position: absolute; right: 25px;">
                        <i class="bi bi-trash"></i>
                    </button>
                    {% endif %}
                </div>

                <div class="comment-content">
                    <p>{{ reply.comment_content }}</p>
                    <small class="ms-0 text-muted">{{ reply.comment_time }}</small>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>



  
  <script>
  function confirmDelete(postId) {
    if (confirm("Do you want to delete this?")) {
      // Redirect to the delete post URL
      window.location.href = "{% url 'posting:delete_comment' %}?post_id=" + postId;
    }
  }
  </script>

{% endblock 'content' %}

fikrin/templates/sidebar.html
{% load static %}

<div class="container-fluid"> 
    <div class="row">
      <div class="sidebar border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
        <div class="offcanvas-lg offcanvas-end d-flex flex-column flex-shrink-0 bg-light justify-content-center rounded-2" id="sidebarMenu" aria-labelledby="sidebarMenuLabel"
         style="width: 3rem; height: 200px; position: fixed; right: 4px; margin-top: 75px; ">
    
            <ul class="nav nav-pills nav-flush flex-column text-center">
              <li>
                  <a {% if user.is_authenticated %} href="{% url 'authentication:profile' %}" {% endif %} class="nav-link py-3" aria-current="page" title="Profile" data-bs-toggle="tooltip" data-bs-placement="right">
                    <i class="bi bi-person-circle pe-none" width="24" height="24" role="img" aria-label="Products" style="color: #000157;"></i>
                  </a>
              </li>
    
              <li>
                <a class="nav-link py-3" title="Quotes" {% if user.is_authenticated %} data-bs-toggle="modal" {% endif %} data-bs-target="#exampleModal" data-bs-placement="right">
                  <i class="bi bi-vector-pen pe-none" width="24" height="24" role="img" aria-label="Products" style="color: #000157;"></i>
                </a>
              </li> 

              <li>
                <a href="{% url 'authentication:aboutme' %}" class="nav-link py-3 " title="About us" data-bs-toggle="tooltip" data-bs-placement="right">
                  <i class="bi bi-info-circle pe-none" width="24" height="24" role="img" aria-label="Products" style="color: #000157;"></i>
                </a>
              </li>
    
            </ul>
    
        </div>
      </div>
    
    </div>
    </div>
    
    <header>